// Additional offers data for Offer Alert Bot
const moreOffers = [
  {
    id: 33,
    title: "Dell XPS 13 Laptop",
    description: "Ultra-thin laptop with InfinityEdge display",
    originalPrice: 129990,
    discountedPrice: 109990,
    discount: 15,
    category: "Electronics",
    platform: "Dell",
    image: "https://images.unsplash.com/photo-1593642702821-c8da6771f0c6?w=400",
    link: "https://www.dell.com/en-in/shop/laptops-2-in-1-pcs/sr/laptops/xps-laptops",
    rating: 4.7,
    reviews: 1230
  },
  {
    id: 34,
    title: "Bose QuietComfort Earbuds II",
    description: "Wireless noise cancelling earbuds with personalized sound",
    originalPrice: 29900,
    discountedPrice: 24900,
    discount: 17,
    category: "Electronics",
    platform: "Bose",
    image: "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f37?w=400",
    link: "https://www.boseindia.com/en_in/products/headphones/earbuds/quietcomfort-earbuds-ii.html",
    rating: 4.8,
    reviews: 890
  },
  {
    id: 35,
    title: "IKEA BILLY Bookcase",
    description: "Versatile bookcase with adjustable shelves",
    originalPrice: 7999,
    discountedPrice: 5999,
    discount: 25,
    category: "Home & Furniture",
    platform: "IKEA",
    image: "https://images.unsplash.com/photo-1588629570566-2a4d6dc05416?w=400",
    link: "https://www.ikea.com/in/en/p/billy-bookcase-white-s69017828/",
    rating: 4.5,
    reviews: 3450
  },
  {
    id: 36,
    title: "Fitbit Sense 2 Advanced Smartwatch",
    description: "Health and fitness smartwatch with stress management",
    originalPrice: 24999,
    discountedPrice: 19999,
    discount: 20,
    category: "Electronics",
    platform: "Amazon",
    image: "https://images.unsplash.com/photo-1575311373937-040b8e1fd6b5?w=400",
    link: "https://www.amazon.in/s?k=fitbit+sense+2",
    rating: 4.3,
    reviews: 780
  },
  {
    id: 37,
    title: "Philips Air Fryer XXL",
    description: "Large capacity air fryer with fat removal technology",
    originalPrice: 14999,
    discountedPrice: 9999,
    discount: 33,
    category: "Home Appliances",
    platform: "Flipkart",
    image: "https://images.unsplash.com/photo-1626074353765-517a681e40be?w=400",
    link: "https://www.flipkart.com/search?q=philips+air+fryer+xxl",
    rating: 4.6,
    reviews: 1120
  },
  {
    id: 38,
    title: "Lululemon Align Leggings",
    description: "Buttery-soft yoga pants for ultimate comfort",
    originalPrice: 9800,
    discountedPrice: 7840,
    discount: 20,
    category: "Fashion",
    platform: "Lululemon",
    image: "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=400",
    link: "https://www.lululemon.co.in/en-in/p/women-pants/Align-High-Rise-Pant-28%22/_/prod8780551",
    rating: 4.9,
    reviews: 5670
  },
  {
    id: 39,
    title: "Dyson V12 Detect Slim Vacuum",
    description: "Lightweight cordless vacuum with laser dust detection",
    originalPrice: 58900,
    discountedPrice: 49900,
    discount: 15,
    category: "Home Appliances",
    platform: "Dyson",
    image: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?w=400",
    link: "https://www.dyson.in/vacuum-cleaners/cordless/v12-detect-slim",
    rating: 4.7,
    reviews: 890
  },
  {
    id: 40,
    title: "Weber Original Kettle Premium Charcoal Grill",
    description: "Classic charcoal grill with one-touch cleaning system",
    originalPrice: 22999,
    discountedPrice: 18999,
    discount: 17,
    category: "Home & Garden",
    platform: "Amazon",
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=400",
    link: "https://www.amazon.in/s?k=weber+original+kettle+premium",
    rating: 4.8,
    reviews: 2340
  },
  {
    id: 41,
    title: "Casio G-Shock GA-2100 Watch",
    description: "Octagonal bezel watch with carbon core guard",
    originalPrice: 8995,
    discountedPrice: 6995,
    discount: 22,
    category: "Fashion",
    platform: "Casio",
    image: "https://images.unsplash.com/photo-1623998021446-45cd9b457d63?w=400",
    link: "https://www.casio.com/in/watches/gshock/product.GA-2100/",
    rating: 4.7,
    reviews: 1560
  },
  {
    id: 42,
    title: "Instant Pot Duo Evo Plus",
    description: "10-in-1 multi-use programmable pressure cooker",
    originalPrice: 12999,
    discountedPrice: 8999,
    discount: 31,
    category: "Home Appliances",
    platform: "Flipkart",
    image: "https://images.unsplash.com/photo-1585664811087-47f65abbad64?w=400",
    link: "https://www.flipkart.com/search?q=instant+pot+duo+evo+plus",
    rating: 4.6,
    reviews: 3450
  },
  {
    id: 43,
    title: "Kindle Scribe Digital Notebook",
    description: "E-reader with writing capabilities and 10.2\" display",
    originalPrice: 34999,
    discountedPrice: 29999,
    discount: 14,
    category: "Electronics",
    platform: "Amazon",
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400",
    link: "https://www.amazon.in/s?k=kindle+scribe",
    rating: 4.5,
    reviews: 780
  },
  {
    id: 44,
    title: "Theragun Elite Massage Gun",
    description: "Premium percussive therapy device for muscle recovery",
    originalPrice: 34999,
    discountedPrice: 29999,
    discount: 14,
    category: "Health & Fitness",
    platform: "Therabody",
    image: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400",
    link: "https://www.therabody.com/in/en-in/theragun-elite/",
    rating: 4.7,
    reviews: 890
  },
  {
    id: 45,
    title: "Nespresso Vertuo Next Coffee Machine",
    description: "Coffee maker with 5 cup sizes and Bluetooth connectivity",
    originalPrice: 19999,
    discountedPrice: 14999,
    discount: 25,
    category: "Home Appliances",
    platform: "Nespresso",
    image: "https://images.unsplash.com/photo-1585060544812-6b45742d762f?w=400",
    link: "https://www.nespresso.com/in/en/order/machines/vertuo",
    rating: 4.6,
    reviews: 1230
  },
  {
    id: 46,
    title: "Lego Star Wars Millennium Falcon",
    description: "Ultimate collector's edition with 7,541 pieces",
    originalPrice: 69999,
    discountedPrice: 59999,
    discount: 14,
    category: "Toys & Games",
    platform: "Lego",
    image: "https://images.unsplash.com/photo-1518331647614-7a1f04cd34cf?w=400",
    link: "https://www.lego.com/en-in/product/millennium-falcon-75192",
    rating: 4.9,
    reviews: 2340
  },
  {
    id: 47,
    title: "Vitamix 5200 Blender",
    description: "Professional-grade blender with variable speed control",
    originalPrice: 54999,
    discountedPrice: 44999,
    discount: 18,
    category: "Home Appliances",
    platform: "Amazon",
    image: "https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=400",
    link: "https://www.amazon.in/s?k=vitamix+5200",
    rating: 4.8,
    reviews: 3450
  },
  {
    id: 48,
    title: "Sonos Arc Premium Soundbar",
    description: "Smart soundbar with Dolby Atmos and voice control",
    originalPrice: 87999,
    discountedPrice: 74999,
    discount: 15,
    category: "Electronics",
    platform: "Sonos",
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=400",
    link: "https://www.sonos.com/en-in/shop/arc",
    rating: 4.7,
    reviews: 1560
  },
  {
    id: 49,
    title: "Le Creuset Signature Cast Iron Round Dutch Oven",
    description: "Premium enameled cast iron cookware, 5.5 quart",
    originalPrice: 32999,
    discountedPrice: 26999,
    discount: 18,
    category: "Home & Kitchen",
    platform: "Le Creuset",
    image: "https://images.unsplash.com/photo-1585837575652-267cbc187fc3?w=400",
    link: "https://www.lecreuset.co.in/en_IN/p/cast-iron-round-dutch-oven/CI1177.html",
    rating: 4.9,
    reviews: 890
  },
  {
    id: 50,
    title: "Oculus Quest 2 VR Headset",
    description: "All-in-one virtual reality headset with 256GB storage",
    originalPrice: 44999,
    discountedPrice: 39999,
    discount: 11,
    category: "Gaming",
    platform: "Meta",
    image: "https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?w=400",
    link: "https://www.meta.com/in/quest/products/quest-2/",
    rating: 4.8,
    reviews: 5670
  },
  {
    id: 51,
    title: "Breville Barista Express Espresso Machine",
    description: "Semi-automatic espresso machine with built-in grinder",
    originalPrice: 59999,
    discountedPrice: 49999,
    discount: 17,
    category: "Home Appliances",
    platform: "Breville",
    image: "https://images.unsplash.com/photo-1612888077748-00e3bf89b56c?w=400",
    link: "https://www.breville.in/products/espresso/the-barista-express",
    rating: 4.7,
    reviews: 2340
  },
  {
    id: 52,
    title: "Patagonia Down Sweater Jacket",
    description: "Lightweight, windproof, and water-resistant down jacket",
    originalPrice: 16999,
    discountedPrice: 13599,
    discount: 20,
    category: "Fashion",
    platform: "Patagonia",
    image: "https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=400",
    link: "https://www.patagonia.com/product/mens-down-sweater-jacket/84674.html",
    rating: 4.8,
    reviews: 1230
  },
  {
    id: 53,
    title: "Atomic Habits by James Clear",
    description: "Bestselling self-help book for building good habits and breaking bad ones",
    originalPrice: 799,
    discountedPrice: 499,
    discount: 37,
    category: "Books",
    platform: "Amazon",
    image: "https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=400",
    link: "https://www.amazon.in/s?k=atomic+habits",
    rating: 4.8,
    reviews: 45230
  },
  {
    id: 54,
    title: "Organic Grocery Essentials Combo Pack",
    description: "Curated combo of organic staples including rice, dal, and spices",
    originalPrice: 2499,
    discountedPrice: 1799,
    discount: 28,
    category: "Grocery",
    platform: "BigBasket",
    image: "https://images.unsplash.com/photo-1580915411954-282cb1c9c450?w=400",
    link: "https://www.bigbasket.com/ps/?q=organic+combo",
    rating: 4.5,
    reviews: 3890
  },
  {
    id: 55,
    title: "Nykaa Luxe Skin Care Kit",
    description: "Premium skin care combo with cleanser, serum, and moisturizer",
    originalPrice: 3999,
    discountedPrice: 2699,
    discount: 33,
    category: "Beauty & Personal Care",
    platform: "Nykaa",
    image: "https://images.unsplash.com/photo-1512496015851-a90fb38ba796?w=400",
    link: "https://www.nykaa.com/search/result/?q=skin+care+kit",
    rating: 4.6,
    reviews: 5640
  },
  {
    id: 56,
    title: "Decathlon Home Workout Starter Kit",
    description: "All-in-one home workout kit with dumbbells, resistance bands, and yoga mat",
    originalPrice: 6999,
    discountedPrice: 4999,
    discount: 29,
    category: "Sports & Fitness",
    platform: "Decathlon",
    image: "https://images.unsplash.com/photo-1599058945522-28d584b6f0ff?w=400",
    link: "https://www.decathlon.in/search?query=home+workout+kit",
    rating: 4.7,
    reviews: 2430
  }
];

module.exports = moreOffers;
